---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Introduction
    - name: module-02
      label: Deploy a container image into an interactive container runtime
    - name: module-03
      label: Administer the container
    - name: module-04
      label: Deploy a container image into a detached container runtime
    - name: module-05
      label: Cleanup
tabs:
  - name: ">_ Podman"
    port: 443
    path: /tty1
    user: root
    host: rhel 
  - name: ">_ RHEL Host"
    port: 443
    path: /tty1
    user: root
    host: rhel
