= Deploy a container image into a detached container runtime

Running an interactive container is all well and good, however, if the
container is offering applications or services, you do not need to
interact with it.

The *rhel9-httpd* container, for example, is configured with an Apache
web server running within it. You will create a new instance of this
container in a detached mode. Further, the command provided will
configure port forwarding for the Apache web server so that connections
to the host’s port 8081 will redirect to the running container’s port 8080.

Run the following command in the `+Podman+` tab.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman run -dt -p 8081:8080/tcp rhel9-httpd
----

You can verify the state of the container using *podman ps*

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman ps -a
----

.Output
[source,text]
----
CONTAINER ID  IMAGE                         COMMAND               CREATED        STATUS        PORTS                   NAMES
435145543bf6  localhost/rhel9-httpd:latest  /usr/bin/run-http...  2 minutes ago  Up 2 minutes  0.0.0.0:8081->8080/tcp  sweet_wu
----

Observe that the `STATUS` is `Up` and there is a new section in the output `PORTS` that indicates the port forwarding defined for the container.

Test the webserver on the container with the `curl` command.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
curl localhost:8081
----

This should now display the Apache test page, being served by the httpd
daemon running in the container.

.Output
[source,text]
----
<< OUTPUT ABRIDGED >>

    </div>
<div class="footer">
    <a href="https://apache.org">Apache&trade;</a> is a registered trademark of <a href="https://apache.org">the Apache Software Foundation</a> in the United States and/or other countries.
<br />
    <a href="https://nginx.com">NGINX&trade;</a> is a registered trademark of <a href="https://www.f5.com">F5 Networks, Inc.</a>.
</div>
----
